targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            "{{dir}}/{{file}}.dart": ["{{dir}}/_gen/{{file}}.g.dart"]
      json_serializable:
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: true
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: false
      copy_with_extension_gen:
        options:
          generate_for:
            - lib/src/models/**
