# Test: Discriminator property doesn't exist in schemas (should fail validation)
openapi: 3.0.0
info:
  title: Invalid Discriminator Property Missing Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: animalType  # This property doesn't exist!
    
    Cat:
      type: object
      required: [name, meow]
      properties:
        name:
          type: string
        meow:
          type: boolean
    
    Dog:
      type: object
      required: [name, bark]
      properties:
        name:
          type: string
        bark:
          type: boolean

