# Test: allOf with different const values (should fail validation)
openapi: 3.0.0
info:
  title: Invalid AllOf Different Const Test
  version: 1.0.0
paths: {}
components:
  schemas:
    InvalidAllOfDifferentConst:
      allOf:
        - const: "foo"
        - const: "bar"
