# Test: Discriminator property has inconsistent types (should fail validation)
openapi: 3.0.0
info:
  title: Invalid Discriminator Inconsistent Types Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: petType
    
    Cat:
      type: object
      required: [petType, meow]
      properties:
        petType:
          type: string  # string type
        meow:
          type: boolean
    
    Dog:
      type: object
      required: [petType, bark]
      properties:
        petType:
          type: integer  # integer type - inconsistent!
        bark:
          type: boolean

