# Test: discriminator without composition keyword (should fail validation)
openapi: 3.0.0
info:
  title: Invalid Discriminator Without Composition Test
  version: 1.0.0
paths: {}
components:
  schemas:
    InvalidDiscriminatorAlone:
      type: object
      required: [petType]
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
