# Test: Duplicate references in oneOf (should fail validation)
openapi: 3.0.0
info:
  title: Invalid Duplicate Refs Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Cat:
      type: object
      properties:
        meow:
          type: boolean

    InvalidDuplicateRefs:
      oneOf:
        - $ref: "#/components/schemas/Cat"
        - $ref: "#/components/schemas/Cat"
