# Test: Discriminator property is not a string type (should fail validation)
openapi: 3.0.0
info:
  title: Invalid Discriminator Non-String Type Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: petType
    
    Cat:
      type: object
      required: [petType, meow]
      properties:
        petType:
          type: integer  # Should be string for discriminators
        meow:
          type: boolean
    
    Dog:
      type: object
      required: [petType, bark]
      properties:
        petType:
          type: integer  # Should be string for discriminators
        bark:
          type: boolean

